### ISSUE TITLE
How to make "Preserves the folder structure" work?

### ISSUE THREAD

**Issue by NSFish** [leavez/cocoapods-developing-folder#2]
Hello, I was looking for a solution to preserve the folder structure when developing my pod and came across your project.

### Problem ###
I was trying out the template workspace produced by
`pod lib create DummyPod`
After I added several files under DummyPod/Classes, and run 
`pod install`
I was expecting my development pod structure to be like this
![image](https://user-images.githubusercontent.com/3808102/49931369-adc1a780-ff01-11e8-88ec-c5c0c90bfc53.png)
Which was how these files being structured on the file system. But what I got was this
![image](https://user-images.githubusercontent.com/3808102/49931405-bd40f080-ff01-11e8-84ce-7cd6c2fc2f19.png)

### Possible Reason ###
According to [this issue](https://github.com/CocoaPods/CocoaPods/issues/4719), cocoapods would just drop any root path that is shared between all files. So in my case, the "Sources" was being dropped out. 

### Is "use_folder" supposed to work in this case? ###
I've tried to combine both local_pod and folder with use_folder, and the structure of DummyPod in Xcode stay the same.

Is this intented?

**Comment by leavez** [comment]
Sorry for the lack of description. “Preserves the folder structure" only is valid for the structures above pod_root.

For example, “peoject_root/Modules/Core/DummyPod/DummyPod.podspec”, it will preserve "Modules/Core"
